skillMetadata:
  sections:
    - name: Settings
      fields:
        - name: OpenAI key
          type: password
          label: access token
          //change value to hold api key
          value: ""
          placeholder: token
